[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
onchain_blog = "FHMvSSY4Ne9j7Zgjcus5VBCtW2yykTQfnTXxiuVYbauX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./oeBfrXU7Yu8JsaZgbLSddYgkhn6TvaQ4Ywt2PDZov67.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
